all:	program0 program1 program2 program3 program4 program5 program6 program7 program 8 

program0:
	gcc -Wall -Wextra -Werror ./ex00/ft_strcmp.c main00.c -o program0

program1:
	gcc -Wall -Wextra -Werror ./ex00/ft_strcmp.c main01.c -o program1

program2:
	gcc -Wall -Wextra -Werror ./ex00/ft_strcmp.c main02.c -o program2

program3:
	gcc -Wall -Wextra -Werror ./ex00/ft_strcmp.c main03.c -o program3

program4:
	gcc -Wall -Wextra -Werror ./ex00/ft_strcmp.c main04.c -o program4

program5:
	gcc -Wall -Wextra -Werror ./ex00/ft_strcmp.c main05.c -o program5

program6:
	gcc -Wall -Wextra -Werror ./ex00/ft_strcmp.c main06.c -o program6

program7:
	gcc -Wall -Wextra -Werror ./ex00/ft_strcmp.c main07.c -o program7

program7:
	gcc -Wall -Wextra -Werror ./ex00/ft_strcmp.c main08.c -o program8


